name: rescue_pitchtech
description: >
  Rescue Pitchtech — landing page de gestão de emergência em Flutter.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  rescue_design_system:
    path: ../rescue_design_system

  get_it: ^8.0.3
  equatable: ^2.0.7
  dartz: ^0.10.1
  dio: ^5.8.0+1
  url_launcher: ^6.3.1
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  mocktail: ^1.0.4
  flutter_launcher_icons: ^0.14.4

flutter:
  config:
    enable-lldb-debugging: false
  uses-material-design: true
  assets:
    - assets/imagens/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/imagens/app_icon.png"
  min_sdk_android: 21
  adaptive_icon_background: "#0B2340"
  adaptive_icon_foreground: "assets/imagens/app_icon_foreground.png"
  remove_alpha_ios: true
  web:
    generate: true
    image_path: "assets/imagens/app_icon.png"
    background_color: "#0B2340"
    theme_color: "#0B2340"
  windows:
    generate: true
    image_path: "assets/imagens/app_icon.png"
    icon_size: 48
  macos:
    generate: true
    image_path: "assets/imagens/app_icon.png"
